# Generated by Django 5.2 on 2025-04-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
